---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-goodies-demo-istio-bookinfo
  namespace: argocd

  # https://argoproj.github.io/argo-cd/user-guide/compare-options/
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous

  # finalizers:  # Add a this finalizer ONLY if you want these to cascade delete.
  #   - resources-finalizer.argocd.argoproj.io 

spec:
  project: default
  source:
    directory:
      recurse: true
    repoURL: https://github.com/istio/istio.git
    targetRevision: HEAD
    path: samples/bookinfo/platform/kube/bookinfo.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
    
  # Sync policy
  syncPolicy:
    automated:
      prune: false # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: false # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).

