---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

#
# Ordered list of application manifests to install
#
resources:
  - manifests/podinfo-demo.yaml
  # - gloo-petclinic.yaml
  # - gloo-petstore.yaml
